const brandModels = {
  "Abarth": ["595", "695", "124 Spider"],
  "Alfa Romeo": ["Giulia", "Stelvio", "Tonale", "Giulietta", "MiTo"],
  "Aston Martin": ["DB11", "Vantage", "DBX", "DBS Superleggera"],
  "Audi": ["A1", "A3", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q5", "Q7", "Q8", "e-tron", "RS3", "RS6", "TT", "R8"],
  "Bentley": ["Continental GT", "Flying Spur", "Bentayga"],
  "BMW": ["Série 1", "Série 2", "Série 3", "Série 4", "Série 5", "Série 7", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "Z4", "i4", "iX", "M3", "M4", "M5"],
  "Bugatti": ["Chiron", "Veyron", "Divo"],
  "Cadillac": ["Escalade", "CT5", "XT5", "Lyriq"],
  "Chevrolet": ["Camaro", "Corvette", "Spark", "Trax", "Malibu"],
  "Chrysler": ["300", "Pacifica", "Voyager"],
  "Citroën": ["C1", "C3", "C3 Aircross", "C4", "C4 X", "C5 Aircross", "Berlingo", "ë-C4"],
  "Dacia": ["Sandero", "Duster", "Jogger", "Spring", "Logan"],
  "Daewoo": ["Matiz", "Kalos", "Lacetti"],
  "Daihatsu": ["Sirion", "Terios", "Copen"],
  "Dodge": ["Charger", "Challenger", "Durango", "Ram"],
  "Donkervoort": ["D8 GTO", "F22"],
  "DS": ["DS 3", "DS 4", "DS 7", "DS 9"],
  "Ferrari": ["Roma", "Portofino", "F8 Tributo", "SF90", "296 GTB", "812", "Purosangue"],
  "Fiat": ["500", "500X", "500L", "Panda", "Tipo", "Punto", "Doblo"],
  "Fisker": ["Ocean", "Pear"],
  "Ford": ["Fiesta", "Focus", "Puma", "Kuga", "Mustang", "Explorer", "Ranger", "Transit", "Mondeo", "Galaxy", "EcoSport"],
  "Honda": ["Civic", "Jazz", "HR-V", "CR-V", "ZR-V", "e:Ny1", "Accord"],
  "Hummer": ["H2", "H3", "EV"],
  "Hyundai": ["i10", "i20", "i30", "Tucson", "Kona", "Santa Fe", "IONIQ 5", "IONIQ 6", "Bayon"],
  "Infiniti": ["Q50", "Q60", "QX50", "QX80"],
  "Iveco": ["Daily", "S-Way", "Eurocargo"],
  "Jaguar": ["XE", "XF", "F-Pace", "E-Pace", "I-Pace", "F-Type"],
  "Jeep": ["Renegade", "Compass", "Cherokee", "Grand Cherokee", "Wrangler", "Avenger"],
  "Kia": ["Picanto", "Rio", "Ceed", "Sportage", "Sorento", "Niro", "EV6", "Stinger", "Stonic"],
  "KTM": ["X-Bow"],
  "Lada": ["Niva", "Vesta", "Granta"],
  "Lamborghini": ["Huracán", "Urus", "Revuelto", "Aventador"],
  "Lancia": ["Ypsilon", "Delta"],
  "Land Rover": ["Defender", "Discovery", "Discovery Sport", "Range Rover", "Range Rover Sport", "Range Rover Velar", "Range Rover Evoque"],
  "Landwind": ["X7", "X8"],
  "Lexus": ["IS", "ES", "LS", "UX", "NX", "RX", "LX", "LC", "RZ"],
  "Lotus": ["Emira", "Eletre", "Evija"],
  "Maserati": ["Ghibli", "Levante", "Quattroporte", "MC20", "GranTurismo", "Grecale"],
  "Maybach": ["S 580", "S 680", "GLS 600"],
  "Mazda": ["Mazda2", "Mazda3", "Mazda6", "CX-3", "CX-30", "CX-5", "CX-60", "MX-5", "MX-30"],
  "McLaren": ["720S", "Artura", "GT", "765LT"],
  "Mercedes-Benz": ["Classe A", "Classe B", "Classe C", "Classe E", "Classe S", "CLA", "CLS", "GLA", "GLB", "GLC", "GLE", "GLS", "G63", "220d", "AMG GT", "EQA", "EQB", "EQC", "EQE", "EQS", "Vito"],
  "MG": ["MG4", "ZS", "HS", "Marvel R", "MG5"],
  "Mini": ["Cooper", "Clubman", "Countryman", "Cabrio"],
  "Mitsubishi": ["ASX", "Eclipse Cross", "Outlander", "Space Star", "L200"],
  "Morgan": ["Plus Four", "Plus Six", "Super 3"],
  "Nissan": ["Micra", "Juke", "Qashqai", "X-Trail", "Leaf", "Ariya", "GT-R", "Navara", "370Z"],
  "Opel": ["Corsa", "Astra", "Mokka", "Crossland", "Grandland", "Insignia", "Combo"],
  "Peugeot": ["208", "308", "408", "508", "2008", "3008", "5008", "Rifter", "e-208", "e-2008"],
  "Porsche": ["911", "718 Cayman", "718 Boxster", "Cayenne", "Macan", "Panamera", "Taycan"],
  "Renault": ["Clio", "Captur", "Mégane", "Arkana", "Austral", "Espace", "Kangoo", "Zoe", "Twingo", "Scénic"],
  "Rolls-Royce": ["Phantom", "Ghost", "Wraith", "Dawn", "Cullinan", "Spectre"],
  "Rover": ["25", "45", "75"],
  "Saab": ["9-3", "9-5"],
  "Seat": ["Ibiza", "Leon", "Arona", "Ateca", "Tarraco"],
  "Skoda": ["Fabia", "Scala", "Octavia", "Superb", "Kamiq", "Karoq", "Kodiaq", "Enyaq"],
  "Smart": ["ForTwo", "ForFour", "#1"],
  "SsangYong": ["Tivoli", "Korando", "Rexton", "Torres"],
  "Subaru": ["Impreza", "XV", "Forester", "Outback", "BRZ", "Solterra"],
  "Suzuki": ["Swift", "Ignis", "Vitara", "S-Cross", "Jimny", "Across"],
  "Tesla": ["Model 3", "Model Y", "Model S", "Model X", "Cybertruck"],
  "Toyota": ["Yaris", "Yaris Cross", "Corolla", "Camry", "C-HR", "RAV4", "Highlander", "Land Cruiser", "Supra", "GR86", "Aygo X", "bZ4X", "Hilux"],
  "Volkswagen": ["Polo", "Golf", "T-Roc", "T-Cross", "Tiguan", "Touareg", "Passat", "Arteon", "ID.3", "ID.4", "ID.5", "ID. Buzz", "Caddy", "Transporter"],
  "Volvo": ["XC40", "XC60", "XC90", "S60", "S90", "V60", "V90", "C40", "EX30", "EX90"]
};

module.exports = {
  brandModels,
  brands: Object.keys(brandModels)
};
